apiVersion: v2
appVersion: 20.12-py3
description: Jupyter Notebook with PyTorch chart
name: jupyter
version: 0.0.5
kubeVersion: ">=1.16.0-0"
home: https://github.com/sennerholm/nvidia-charts/charts/tree/master/charts/pytorch
maintainers:
- name: Mikael Sennerholm
  email: mikael@sennerholm.net
dependencies:
- name: common
  version: 2.1.0
  repository: https://library-charts.k8s-at-home.com
